Areas/Admin/Controllers/CouponController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xSteak.Data;
using xSteak.Models;
using xSteak.Utility;

namespace xSteak.Areas.Admin.Controllers
{
    [Authorize(Roles =(SD.ManagerUser))]
    [Area("Admin")]
    public class CouponController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CouponController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _db.Coupon.ToListAsync());
        }

        //GET Coupon 
        public IActionResult Create()
        {
            return View();
        }

        //Post Coupon 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Coupon coupons)
        {
            if (ModelState.IsValid)
            {
                var files = Request.Form.Files;
                if (files.Count > 0)
                {
                    byte[] p1 = null;
                    using (var fs1 = files[0].OpenReadStream())
                    {
                        using (var ms1 = new MemoryStream())
                        {
                            fs1.CopyTo(ms1);
                            p1 = ms1.ToArray();
                        }
                    }
                    coupons.Picture = p1;
                }
                _db.Coupon.Add(coupons);
                await _db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(coupons);
        }

        //GET edit 
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            return View(await _db.Coupon.FindAsync(id));
        }

        //Post-Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Edit")]

        public async Task<IActionResult> EditPost(int id, Coupon coupons)
        {
            var coup = _db.Coupon.Find(id);
            var files = Request.Form.Files;
            if (files.Count > 0)
            {
                byte[] p1 = null;
                using (var fs1 = files[0].OpenReadStream())
                {
                    using (var ms1 = new MemoryStream())
                    {
                        fs1.CopyTo(ms1);
                        p1 = ms1.ToArray();
                    }
                }
                coupons.Picture = p1;
            }
            coup.MinimumAmount = coupons.MinimumAmount;
            coup.Name = coupons.Name;
            coup.Discount = coupons.Discount;
            coup.CouponType = coupons.CouponType;
            coup.IsActive = coupons.IsActive;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //GET Details 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _db.Coupon.FindAsync(id));
        }
        //Get Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(await _db.Coupon.FindAsync(id));
        }

        //Post Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int id)
        {
            var coupon = await _db.Coupon.FindAsync(id);
            _db.Coupon.Remove(coupon);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

    }


}

Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xSteak.Data;
using xSteak.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace xSteak.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = (SD.ManagerUser))]
    public class UserController : Controller
    {

        private readonly ApplicationDbContext _db;
        public UserController(ApplicationDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(await _db.ApplicationUser.Where(x=>x.Id!=claim.Value && x.JopType!=null).ToListAsync());
        }

        public async Task<IActionResult> Lock (string id)
        {
            if (id==null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser==null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now.AddYears(1000);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> UnLock(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var applicationUser = await _db.ApplicationUser.FirstOrDefaultAsync(m => m.Id == id);
            if (applicationUser == null)
            {
                return NotFound();
            }
            applicationUser.LockoutEnd = DateTime.Now;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
        public async Task<IActionResult> Delete (string id)
        {
            var user = _db.ApplicationUser.Find(id);
            _db.Remove(user);
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
    }
}

Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using xSteak.Data;
using xSteak.Models;
using xSteak.Models.ViewModels;
using xSteak.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;
using Stripe;

namespace xSteak.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _db;
        [BindProperty]
        public OrderDetailsCart detailsCart { get; set; }
        public readonly IEmailSender EmailSender;
        public CartController(ApplicationDbContext db , IEmailSender emailSender )

        {
            EmailSender = emailSender;
            _db = db;
        }

        [Authorize(Roles = SD.CustomerEndUser + "," + SD.ManagerUser + "," + SD.KitchenUser + "," + SD.FrontDeskUser)]
        public async Task< IActionResult> Index()
        {

            detailsCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };
            detailsCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var cart = _db.ShoppingCart.Where(x => x.ApplicationUserId == claim.Value);

            if (cart!=null)
            {
                detailsCart.ListCart = cart.ToList();
            }
            foreach (var list in detailsCart.ListCart)
            {
                list.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(m=>m.Id==list.MenuItemId);
                if (list.MenuItem == null)
                {
                    continue;
                }
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);
                
            }
            detailsCart.OrderHeader.OrderTotalOriginal = detailsCart.OrderHeader.OrderTotal;
           
           
            return View(detailsCart);
        }

        //Summary

        public async Task<IActionResult> Summary()
        {

            detailsCart = new OrderDetailsCart()
            {
                OrderHeader = new Models.OrderHeader()
            };
            detailsCart.OrderHeader.OrderTotal = 0;

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var cart = _db.ShoppingCart.Where(x => x.ApplicationUserId == claim.Value);
            ApplicationUser applicationUser = await _db.ApplicationUser.Where(x => x.Id == claim.Value).FirstOrDefaultAsync();
            if (cart != null)
            {
                detailsCart.ListCart = cart.ToList();
            }
            foreach (var list in detailsCart.ListCart)
            {
                list.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(m => m.Id == list.MenuItemId);
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotal + (list.MenuItem.Price * list.Count);

            }
            detailsCart.OrderHeader.OrderTotalOriginal = detailsCart.OrderHeader.OrderTotal;
            detailsCart.OrderHeader.PickupName = applicationUser.Name;
            detailsCart.OrderHeader.PickupNumber = applicationUser.PhoneNumber;
            detailsCart.OrderHeader.PickupDate = DateTime.Now;
            if (HttpContext.Session.GetString("ssCouponCode") != null)
            {
                detailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString("ssCouponCode");
                var couponFromDb = await _db.Coupon.Where(x => x.Name == detailsCart.OrderHeader.CouponCode).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = Discount(couponFromDb, detailsCart.OrderHeader.OrderTotalOriginal);
            }

            return View(detailsCart);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Summary")]
        public async Task<IActionResult> SummaryPost(string stripeToken, OrderDetailsCart detailsCart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            detailsCart.ListCart = await _db.ShoppingCart.Where(c => c.ApplicationUserId == claim.Value).ToListAsync();
            detailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            detailsCart.OrderHeader.OrderDate = DateTime.Now;
            detailsCart.OrderHeader.UserId = claim.Value;
            detailsCart.OrderHeader.Status = SD.PaymentStatusPending;
            detailsCart.OrderHeader.PickupTime = Convert.ToDateTime(detailsCart.OrderHeader.PickupDate.ToShortDateString() + " " + detailsCart.OrderHeader.PickupTime.ToShortTimeString());

            _db.OrderHeader.Add(detailsCart.OrderHeader);
            await _db.SaveChangesAsync();
            detailsCart.OrderHeader.OrderTotalOriginal = 0;

            //Save Order Details 

            List<OrderDetails> orderDetailsList = new List<OrderDetails>();
            foreach (var item in detailsCart.ListCart)
            {
                item.MenuItem = await _db.MenuItems.FirstOrDefaultAsync(m => m.Id == item.MenuItemId);
                OrderDetails orderDetails = new OrderDetails
                {
                    MenuItemId = item.MenuItemId,
                    OrderId = detailsCart.OrderHeader.Id,
                    Description = item.MenuItem.Descrition,
                    Name = item.MenuItem.Name,
                    Price = item.MenuItem.Price,
                    Count = item.Count
                };
                detailsCart.OrderHeader.OrderTotalOriginal += orderDetails.Count * orderDetails.Price;
                _db.OrderDetails.Add(orderDetails);
            }

            if (HttpContext.Session.GetString("ssCouponCode") != null)
            {
                detailsCart.OrderHeader.CouponCode = HttpContext.Session.GetString("ssCouponCode");
                var couponFromDb = await _db.Coupon.Where(x => x.Name == detailsCart.OrderHeader.CouponCode).FirstOrDefaultAsync();
                detailsCart.OrderHeader.OrderTotal = Discount(couponFromDb, detailsCart.OrderHeader.OrderTotalOriginal);
            }
            else
            {
                detailsCart.OrderHeader.OrderTotal = detailsCart.OrderHeader.OrderTotalOriginal;
            }
            detailsCart.OrderHeader.CouponCodeDiscount = detailsCart.OrderHeader.OrderTotalOriginal - detailsCart.OrderHeader.OrderTotal;
            await _db.SaveChangesAsync();
            _db.ShoppingCart.RemoveRange(detailsCart.ListCart);
            HttpContext.Session.SetInt32(SD.ssShoppingCartCount, 0);
            await _db.SaveChangesAsync();

            //Payment method

            var options = new ChargeCreateOptions
            {
                Amount = Convert.ToInt32(detailsCart.OrderHeader.OrderTotal * 100),
                Currency = "usd",
                Description = "Order ID :" + detailsCart.OrderHeader.Id,
                Source = stripeToken
            };
            var service = new ChargeService();
            Charge charge = service.Create(options);
            if (charge.BalanceTransactionId == null)
            {
                detailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            }
            else
            {
                detailsCart.OrderHeader.TransactionId = charge.BalanceTransactionId;

            }
            if (charge.Status.ToLower() == "succeeded")
            {
                //send email to customer
                await EmailSender.SendEmailAsync(_db.Users.Where(x => x.Id == claim.Value)
                    .FirstOrDefault().Email, "xSteak - order Created " + detailsCart.OrderHeader.Id.ToString(),
                    "order has been submitted successfuly");
                detailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
                detailsCart.OrderHeader.Status = SD.StatusSubmitted;
            }
            else
            {
                detailsCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Confirm", "Order", new { id = detailsCart.OrderHeader.Id });
        }




        public IActionResult AddCoupon()
        {
            if (detailsCart.OrderHeader.CouponCode == null)
            {
                detailsCart.OrderHeader.CouponCode = "";
            }
            HttpContext.Session.SetString("ssCouponCode", detailsCart.OrderHeader.CouponCode);
            return RedirectToAction(nameof(Index));
        }


        public IActionResult RemoveCoupon()
        {
            HttpContext.Session.SetString("ssCouponCode", string.Empty);
            return RedirectToAction(nameof(Index));
        }


        // Plus item Count
        public async Task<IActionResult> Plus(int id)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(x => x.Id == id);
            cart.Count += 1;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // Minus item Count
        public async Task<IActionResult> Minus(int id)
        {
            var cart = await _db.ShoppingCart.FirstOrDefaultAsync(x => x.Id == id);
            if (cart.Count == 1)
            {
                _db.ShoppingCart.Remove(cart);
                await _db.SaveChangesAsync();

                var cnt = _db.ShoppingCart.Where(x => x.ApplicationUserId == cart.ApplicationUserId).ToList().Count;
                HttpContext.Session.SetInt32("ssCartCount", cnt);
            }
            else
            {

Views/Shared/_CreateAndBackToListButton.cshtml
<div class="row mt-5">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" value="إنشاء" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control">ارجع الي القائمه السابقه</a>
    </div>
</div>

Views/Shared/_CreateButtonPartial.cshtml
<a asp-action="Create" class="btn btn-info" asp-area="Admin"><i class="fas fa-plus"></i>&nbsp;  إنشاء جديد</a>

Views/Shared/_DeleteAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-danger form-control" asp-route-Id="@Model" value="حذف" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control"> الرجوع الي القائمه السابقه </a>
    </div>
</div>

Views/Shared/_DetailsAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <a asp-action="Edit" asp-route-Id="@Model" class="btn btn-info form-control" > تعديل </a>
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control"> الرجوع الي القائمه السابقه </a>
    </div>
</div>

Views/Shared/_EditAndBackToListButton.cshtml
@model int
<div class="row">
    <div class="col-6">
        <input type="submit" class="btn btn-info form-control" asp-route-Id="@Model" value="تحديث" />
    </div>
    <div class="col-6">
        <a asp-action="Index" class="btn btn-success form-control"> الرجوع الي القائمه السابقه </a>
    </div>
</div>

Views/Shared/_IndividualOrderDetalis.cshtml
@model xSteak.Models.ViewModels.OrderDetalisViewModel
@using xSteak.Utility


<form method="post" asp-action="OrderComplete" asp-controller="ManageOrder" asp-area="Admin" asp-route-id="@Model.OrderHeader.Id">
    <div class="container row border ml-1 backgroundWhite10Padding" style="width:100%">
        <div class="col-lg-8" style="border-right:1px solid #bbb9b9">
            <br />
            <input hidden asp-for="OrderHeader.Id" />
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>الإسم</label>
                </div>
                <div class="col-7">
                    <input asp-for="OrderHeader.PickupName" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>رقم الهاتف</label>
                </div>
                <div class="col-7">
                    <input asp-for="OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>البريد الإلكتروني</label>
                </div>
                <div class="col-7">
                    <input asp-for="OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>المجموع</label>
                </div>
                <div class="col-7">
                    <input asp-for="@Model.OrderHeader.OrderTotal" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>تاريخ الطلب</label>
                </div>
                <div class="col-7">
                    <input value="@Model.OrderHeader.PickupTime.ToShortDateString() @Model.OrderHeader.PickupTime.ToShortTimeString()" disabled class="form-control" />
                </div>
            </div>
            <div class="form-group row">
                <div class="col-3 text-right">
                    <label>إضافات</label>
                </div>
                <div class="col-7">
                    <input asp-for="@Model.OrderHeader.Comments" disabled class="form-control" />
                </div>
            </div>
        </div>

        <div class="col-lg-4 col-12 mt-5">
            <h4 class="d-flex justify-content-between align-content-center mb-3">
                <span class="text-muted">رقم الطلب</span>
                <span class="badge badge-secondary badge-pill">@Model.OrderHeader.Id</span>
            </h4>
            <ul class="list-group mb-3 text-right">
                @{ var total = 0.0; }

                @foreach (var detalis in Model.OrderDetails)
                {
                    <li class="list-group-item d-flex">
                        <div>
                            <h6 class="my-0"> @detalis.Name</h6>
                            <small class="text-muted">الكميه : @detalis.Count</small>
                        </div>
                        <span class="text-muted">@(total+=detalis.Price * detalis.Count) ج</span>
                    </li>
                }
                @if (Model.OrderHeader.CouponCode != null)
                {
                    <li class="list-group-item d-flex justify-content-between">
                        <div class="text-success">
                            <h6 class="my-0"> كوبون الخصم</h6>
                            <small class="text-success">@Model.OrderHeader.CouponCode</small>
                        </div>
                        <span class="text-success">-@(total - Model.OrderHeader.OrderTotal) ج</span>
                    </li>
                }
                <li class="list-group-item d-flex justify-content-between bg-light">
                    <small class="text-info">المطلوب (بالجنيه) </small>
                    <strong class="text-info">@(Model.OrderHeader.OrderTotal) ج</strong>
                </li>
            </ul>
            <div class='mt-5 ml-3 mr-5 d-flex justify-content-between align-content-center'>
                @if ((Model.OrderHeader.Status == SD.StatusReady )&& (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser)))
                {
                    <button type="submit" class="btn btn-success form-control"><i class="far fa-thumbs-up"></i> تأكيد الطلب</button>
                }
                else
                {
                    <button type="button" disabled class="btn btn-info form-control">@Model.OrderHeader.Status</button>
                }
            </div>            
        </div>
    </div>
</form>

Views/Shared/_Layout.cshtml
@using xSteak.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - X Steak </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/jquery-ui.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.10.0/jquery.timepicker.css" />
</head>
<body class="search-background">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">X Steak</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1 ">
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item dropdown text-white-50">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    إداره المحتوي
                                </a>
                                <div class="dropdown-menu text-right" aria-labelledby="navbarDropDownMenuLink">
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Category" asp-area="Admin">النوع</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="SubCategory" asp-area="Admin">نوع فرعي</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="MenuItem" asp-area="Admin">عناصر القائمه</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="Coupon" asp-area="Admin">كوبونات خصم</a>
                                    <a class="dropdown-item" asp-action="Index" asp-controller="User" asp-area="Admin">موظفين</a>

                                </div>
                            </li>

                        }
                        
                    @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.KitchenUser) || User.IsInRole(SD.FrontDeskUser))
                        {
                            <li class="nav-item">

                                @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.KitchenUser))
                                {
                                    <a asp-action="ManageOrder" asp-controller="ManageOrder" asp-area="Admin" class="nav-link">إداره الطلبات</a>
                                }

                            </li>
                            <li class="nav-item">

                                @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.FrontDeskUser))
                                {
                                    <a asp-action="OrderPickup" asp-controller="ManageOrder" asp-area="Admin" class="nav-link">تسليم الطلبات</a>
                                }
                            </li>

                        }
                        @if (User.IsInRole(SD.ManagerUser))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                                    قائمه الطلبات
                                </a>
                            </li>

                        }
                        @if (User.IsInRole(SD.CustomerEndUser))
                        {
                            <li class="nav-item">
                                <a asp-area="Customer" asp-controller="Order" asp-action="OrderHistory" class="nav-link">
                                    تاريخ الطلبات
                                </a>
                            </li>

                        }
                        @if (User.IsInRole(SD.ManagerUser) || User.IsInRole(SD.CustomerEndUser))
                        {

                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    @{
                                        var count = HttpContextAccessor.HttpContext.Session.GetInt32("ssCartCount");
                                    }
                                    <i class="fas fa-shopping-cart"></i> &nbsp;(@count)
                                </a>
                            </li>
                        }
                        @* else
                        {
                            <li style="color:white">
                                <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link">
                                    <i class="fas fa-shopping-cart"></i> &nbsp;(0)
                                </a>
                            </li>
                        } *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50" style="background-color:#343a40">
        <div class="container text-right h4">
            &copy; 2022 - MFCI - X Steak
        </div>
    </footer>

    <script src="https://kit.fontawesome.com/d96434cf54.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_OrderStatus.cshtml
@model string
@using xSteak.Utility
<div style="width:100%">
    @if (Model == SD.StatusSubmitted)
    {
        <img src="~/images/OrderPlaced.png" width="100%" />
    }
    @if (Model == SD.StatusInProcess)
    {
        <img src="~/images/InKitchen.png" width="100%" />
    }
    @if (Model == SD.StatusReady)
    {
        <img src="~/images/ReadyForPickup.png" width="100%" />
    }
    @if (Model == SD.StatusCompleted)
    {
        <img src="~/images/completed.png" width="100%" />
    }
</div>

Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}

Views/Shared/_TableButtonPartial.cshtml
@model int
<td style="width:150px">
    <div class="btn-group" role="group">
        <a class="btn btn-primary text-white mx-1" asp-action="Edit" asp-route-Id="@Model">
            <i class="fas fa-edit"></i>
        </a>
        <a class="btn btn-success text-white mx-1" asp-action="Details" asp-route-Id="@Model">
            <i class="fas fa-list-alt"></i>
        </a>
        <a class="btn btn-danger text-white mx-1" asp-action="Delete" asp-route-Id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>