Areas/Admin/Controllers/ManageOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using xSteak.Data;
using xSteak.Models;
using xSteak.Models.ViewModels;
using xSteak.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace xSteak.Areas.Admin.Controllers
{
    [Area("Admin")]
   
    public class ManageOrderController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IEmailSender EmailSender;
        public ManageOrderController(ApplicationDbContext db, IEmailSender emailSender)
        {
            _db = db;
            EmailSender = emailSender;
        }

        [Authorize(Roles = SD.ManagerUser + "," + SD.KitchenUser)]
        public async Task<IActionResult> ManageOrder()
        {
            List<OrderDetalisViewModel> OrderDetalis = new List<OrderDetalisViewModel>();

            List<OrderHeader> orderHeaders = await _db.OrderHeader.Where(x => x.Status.ToLower() == SD.StatusSubmitted || x.Status.ToLower() == SD.StatusInProcess)
                                             .OrderByDescending(x => x.PickupTime)
                                             .ToListAsync();

            foreach (var item in orderHeaders)
            {
                OrderDetalisViewModel orderDetalisVM = new OrderDetalisViewModel()
                {
                    OrderHeader = item,
                    OrderDetails = await _db.OrderDetails.Where(x => x.OrderId == item.Id).ToListAsync()
                };
                OrderDetalis.Add(orderDetalisVM);
            }
            return View(OrderDetalis.OrderByDescending(x => x.OrderHeader.PickupTime));
        }




        [Authorize(Roles = SD.ManagerUser + "," + SD.KitchenUser)]
        public async Task<IActionResult> OrderPreapare(int id)
        {
            OrderHeader orderHeader = await _db.OrderHeader.FindAsync(id);
            orderHeader.Status = SD.StatusInProcess;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(ManageOrder));
        }



        [Authorize(Roles = SD.ManagerUser + "," + SD.KitchenUser)]
        public async Task<IActionResult> OrderReady(int id)
        {
            OrderHeader orderHeader = await _db.OrderHeader.FindAsync(id);
            orderHeader.Status = SD.StatusReady;
            await _db.SaveChangesAsync();
            //  email logic to notify user that order is read for pickup
            await EmailSender.SendEmailAsync(_db.Users.Where(x => x.Id == orderHeader.UserId).FirstOrDefault().Email, "xSteak -  OrderReady " + orderHeader.Id.ToString(), "order has been Ready successfuly");

            return RedirectToAction(nameof(ManageOrder));
        }




        [Authorize(Roles = SD.ManagerUser + "," + SD.KitchenUser)]
        public async Task<IActionResult> OrderCancel(int id)
        {
            OrderHeader orderHeader = await _db.OrderHeader.FindAsync(id);
            orderHeader.Status = SD.StatusCancelled;
            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(ManageOrder));
        }


        public async Task<IActionResult> OrderComplete(int id)
        {
            _db.OrderHeader.Find(id).Status = SD.StatusCompleted;
            await _db.SaveChangesAsync();
            return RedirectToAction("OrderPickup");
        }



        // Order Details action link
        [Authorize]
        public async Task<IActionResult> OrderPickup(string searchName = null, string searchPhone = null, string searchEmail = null)
        {

            StringBuilder pram = new StringBuilder();
            pram.Append("/Customer/Order/OrderPickup?");
            pram.Append("&searchName");
            if (searchName != null)
            {
                pram.Append(searchName);
            }
            pram.Append("&srearchPhone");
            if (searchPhone != null)
            {
                pram.Append(searchPhone);
            }
            pram.Append("&srearchEmail");
            if (searchEmail != null)
            {
                pram.Append(searchEmail);
            }
            List<OrderDetalisViewModel> orderList = new List<OrderDetalisViewModel>();
            List<OrderHeader> orderHeader = new List<OrderHeader>();
            if (searchPhone != null || searchName != null || searchEmail != null)
            {

                var user = new ApplicationUser();

                if (searchName != null)
                {
                    orderHeader = await _db.OrderHeader.Where(o => o.PickupName.ToLower().Contains(searchName.ToLower()) && o.Status == SD.StatusReady)
                        .OrderByDescending(o => o.OrderDate).ToListAsync();
                }
                else
                {
                    if (searchPhone != null)
                    {
                        orderHeader = await _db.OrderHeader.Where(o => o.PickupNumber.Contains(searchName) && o.Status == SD.StatusReady)
                            .OrderByDescending(o => o.OrderDate).ToListAsync();
                    }
                    else
                    {
                        user = await _db.ApplicationUser.Where(u => u.Email.ToLower().Contains(searchEmail.ToLower())).FirstOrDefaultAsync();
                        if (searchEmail != null)
                        {
                            orderHeader = await _db.OrderHeader.Include(o => o.ApplicationUser)
                                .Where(o => o.UserId == user.Id && o.Status == SD.StatusReady).OrderByDescending(o => o.OrderDate).ToListAsync();
                        }
                    }
                }
            }
            else
            {
                orderHeader = await _db.OrderHeader.Include(o => o.ApplicationUser).Where(x => x.Status == SD.StatusReady).ToListAsync();

            }
            foreach (OrderHeader item in orderHeader)
            {
                OrderDetalisViewModel orderDetalisViewModel = new OrderDetalisViewModel()
                {
                    OrderHeader = item,
                    OrderDetails = await _db.OrderDetails.Where(o => o.OrderId == item.Id).ToListAsync()
                };
                orderList.Add(orderDetalisViewModel);
            }
            return View(orderList);
        }

       

        public async Task<IActionResult> Invoice(int? id)
        {
            OrderDetalisViewModel orderDetalisVM = new OrderDetalisViewModel()
            {
                OrderHeader = await _db.OrderHeader.Include(x => x.ApplicationUser).Where(x => x.Id == id).FirstOrDefaultAsync(),
                OrderDetails = await _db.OrderDetails.Where(x => x.OrderId == id).ToListAsync()
            };

            return View(orderDetalisVM);
        }
    }
}

Areas/Admin/Views/ManageOrder/Invoice.cshtml
@model xSteak.Models.ViewModels.OrderDetalisViewModel

@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


@{
    ViewData["Title"] = "Detalis";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form class="form">
    <br />
    <h2 class="text-info" style="text-align:center">Invoice</h2>
    <br />
    <h5 class="text-info" style="text-align:center">Restaurant Xsteak </h5>
    <br />
    <div style="text-align:center">
        <h4 class="my-0">
            <span>Name :</span>
            <span>@Model.OrderHeader.ApplicationUser.Name</span>


        </h4>
        <h4 class="my-0">

            <span>FrontDesk :</span>
            @if (User.IsInRole(xSteak.Utility.SD.ManagerUser) || User.IsInRole(xSteak.Utility.SD.FrontDeskUser))

            {
                <span>@HttpContextAccessor.HttpContext.Session.GetString(xSteak.Utility.SD.SessionFrontDiskAndManger)</span>
            }

        </h4>
        <h4 class="my-0">

            <span>Order Date :</span>
            <span>@Model.OrderHeader.OrderDate</span>

        </h4>
    </div>
    <br />
    <div class="col-12 form">


        <ul class="list-group mb-3">
            @{ var total = 0.0;
                var a = Model;

            }

            @foreach (var detalis in Model.OrderDetails)
            {
                <li class="list-group-item d-flex justify-content-between">
                    <div>
                        <h6 class="my-0"> @detalis.Name</h6>
                        <small class="text-muted">Quantity : @detalis.Count</small>
                    </div>
                    <span class="text-muted">@(detalis.Price * detalis.Count) ج</span>
                </li>
            }
            @if (Model.OrderHeader.CouponCode != null)
            {
                <li class="list-group-item d-flex justify-content-between">
                    <div class="text-success">
                        <h6 class="my-0"> Promo Code </h6>
                        <small class="text-success">@Model.OrderHeader.CouponCode</small>
                    </div>
                    <span class="text-success">-@(total - Model.OrderHeader.OrderTotal) ج</span>
                </li>
            }
            <li class="list-group-item d-flex justify-content-between bg-light">
                <small class="text-info">Total (EGP) </small>
                <strong class="text-info">@(Model.OrderHeader.OrderTotal) ج</strong>
            </li>

        </ul>
        <div style="text-align: center">
            <input type="button" style="border:dotted" class="btn btn-primary" asp-controller="Order" id="create_pdf" value="print">
            <hr style="background-color:#25b7c4" />
        </div>
    </div>
</form>

@section Scripts{
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>

    <script>
        (function () {
            var
                form = $('.form'),
                cache_width = form.width(),
                a4 = [595.28, 841.89]; // for a4 size paper width and height

            $('#create_pdf').on('click', function () {
                $('body').scrollTop(0);
                createPDF();
            });
            //create pdf
            function createPDF() {
                getCanvas().then(function (canvas) {
                    var
                        img = canvas.toDataURL("image/png"),
                        doc = new jsPDF({
                            unit: 'px',
                            format: 'a4'
                        });
                    doc.addImage(img, 'JPEG', 20, 20);
                    doc.save('Bhavdip-html-to-pdf.pdf');
                    form.width(cache_width);
                });
            }

            // create canvas object
            function getCanvas() {
                form.width((a4[0] * 1.33333) - 80).css('max-width', 'none');
                return html2canvas(form, {
                    imageTimeout: 2000,
                    removeContainer: true
                });
            }

        }());
    </script>
    <script>
        /*
     * jQuery helper plugin for examples and tests
     */
        (function ($) {
            $.fn.html2canvas = function (options) {
                var date = new Date(),
                    $message = null,
                    timeoutTimer = false,
                    timer = date.getTime();
                html2canvas.logging = options && options.logging;
                html2canvas.Preload(this[0], $.extend({
                    complete: function (images) {
                        var queue = html2canvas.Parse(this[0], images, options),
                            $canvas = $(html2canvas.Renderer(queue, options)),
                            finishTime = new Date();

                        $canvas.css({ position: 'absolute', left: 0, top: 0 }).appendTo(document.body);
                        $canvas.siblings().toggle();

                        $(window).click(function () {
                            if (!$canvas.is(':visible')) {
                                $canvas.toggle().siblings().toggle();
                                throwMessage("Canvas Render visible");
                            } else {
                                $canvas.siblings().toggle();
                                $canvas.toggle();
                                throwMessage("Canvas Render hidden");
                            }
                        });
                        throwMessage('Screenshot created in ' + ((finishTime.getTime() - timer) / 1000) + " seconds<br />", 4000);
                    }
                }, options));

                function throwMessage(msg, duration) {
                    window.clearTimeout(timeoutTimer);
                    timeoutTimer = window.setTimeout(function () {
                        $message.fadeOut(function () {
                            $message.remove();
                        });
                    }, duration || 2000);
                    if ($message)
                        $message.remove();
                    $message = $('<div ></div>').html(msg).css({
                        margin: 0,
                        padding: 10,
                        background: "#000",
                        opacity: 0.7,
                        position: "fixed",
                        top: 10,
                        right: 10,
                        fontFamily: 'Tahoma',
                        color: '#fff',
                        fontSize: 12,
                        borderRadius: 12,
                        width: 'auto',
                        height: 'auto',
                        textAlign: 'center',
                        textDecoration: 'none'
                    }).hide().fadeIn().appendTo('body');
                }
            };
        })(jQuery);

    </script>

}

Areas/Admin/Views/ManageOrder/ManageOrder.cshtml
@model IEnumerable<xSteak.Models.ViewModels.OrderDetalisViewModel>
@{
    ViewData["Title"] = "MangeOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2 class="text-info text-right mb-2">إداره الطلبات</h2>

<form method="post">
    @if (Model.Count() > 0)
    {
        <div class="container row bg-white p-2 border mb-3 rounded">
            @foreach (var item in Model)
            {
                <div class="col-12 pb-3 pt-3">
                    <div class="backgroundWhiteBorder10Padding">
                        <div class="row">
                            <div class="col-3 text-right">
                                رقم الطلب : @item.OrderHeader.Id
                                <ul class="text-info">
                                    @foreach (var detalis in item.OrderDetails)
                                    {
                                        <li>@detalis.Name x @detalis.Count</li>

                                    }
                                </ul>
                            </div>
                            <div class="col-4 pb-2">
                                <div class="input-group pb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text">الوقت</span>
                                    </div>
                                    <input type="text" class="border rounded form-control" readonly value="@item.OrderHeader.PickupTime" />
                                </div>
                                @{
                                    var comment = item.OrderHeader.Comments;
                                    if (comment == null || comment.Trim().Length == 0)
                                    {
                                        item.OrderHeader.Comments = "No Instructions";
                                    }

                                }
                                <textarea asp-for="@item.OrderHeader.Comments" readonly class="rounded order form-control" style="width:200px;height:100px;"></textarea>
                            </div>
                            <div class='col-2'></div>
                            <div class="col-3 d-flex align-content-left">
                                @if (item.OrderHeader.Status.Equals(xSteak.Utility.SD.StatusSubmitted))
                                {
                                    <div class="col-12 text-left">
                                        <button type="submit" asp-action="OrderPreapare" asp-route-id="@item.OrderHeader.Id" class="btn btn-info form-control mb-3">
                                            <i class="fas fa-check"></i> &nbsp; ابدأ الطبخ
                                        </button>
                                        <button type="submit" asp-action="OrderCancel" asp-route-id="@item.OrderHeader.Id" class="btn btn-danger form-control mb-3">
                                            <i class="fas fa-check"></i> &nbsp; الغاء الطلب
                                        </button>
                                    </div>
                                }
                                else
                                {
                                    @if (item.OrderHeader.Status.Equals(xSteak.Utility.SD.StatusInProcess))
                                    {
                                        <div class="col-12 ">
                                            <button type="submit" asp-action="OrderReady" asp-route-id="@item.OrderHeader.Id" class="btn btn-success form-control mb-3">
                                                <i class="fas fa-flag-checkered"></i> &nbsp; الطلب جاهز
                                            </button>
                                            <button type="submit" asp-action="OrderCancel" asp-route-id="@item.OrderHeader.Id" class="btn btn-danger form-control mb-3">
                                                <i class="fas fa-times"></i> &nbsp; الغاء الطلب
                                            </button>
                                        </div>
                                    }
                                }
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>

    }

</form>

Areas/Admin/Views/ManageOrder/OrderPickup.cshtml
@model IEnumerable<xSteak.Models.ViewModels.OrderDetalisViewModel>
@using xSteak.Utility
@{
    ViewData["Title"] = "OrderHistory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form method="get">
    <br />
    <br />
    <h2 class="text-info text-right">الطلبات الجاهزه للتسليم :</h2>
    <div class="border backgroundWhite">
        <div class="container" style="height:60px;">
            <div class="row container">
                <div class="col-11 ">
                    <div class="row" style="padding-top:10px">
                        <div class="col-4">
                            @Html.Editor("searchName", new { htmlAttributes = new { @class = "form-control", placeholder = "الإسم..." } })
                        </div>
                        <div class="col-1">
                        <button type="submit" name="submit" value="Search" class="btn btn-info form-control">
                            <i class="fas fa-search"></i>
                        </button>
                        </div>
                        @* <div class="col-4">
                            @Html.Editor("searchPhone", new { htmlAttributes = new { @class = "form-control", placeholder = "رقم الهاتف..." } })
                        </div>
                        <div class="col-4">
                            @Html.Editor("searchEmail", new { htmlAttributes = new { @class = "form-control", placeholder = "البريد الإلكتروني...." } })
                        </div> *@
                    </div>
                </div>                
            </div>

        </div>
        <br />
        <div>
            @if (Model.Count() > 0)
            {
                <table class="table table-striped border">
                    <tr class="table-secondary">
                        <th class='text-right'>
                            @Html.DisplayNameFor(x => x.OrderHeader.Id)
                        </th>
                        <th class='text-right'>
                            @Html.DisplayNameFor(x => x.OrderHeader.PickupName)
                        </th>
                        <th class='text-right'>
                           البريد الإلكتروني
                        </th>
                        <th class='text-right'>
                            @Html.DisplayNameFor(x => x.OrderHeader.PickupTime)
                        </th>
                        <th class='text-right'>
                            @Html.DisplayNameFor(x => x.OrderHeader.OrderTotal)
                        </th>
                        <th class='text-right'>
                            عدد الأصناف
                        </th>

                        <th>

                        </th>
                        <th>

                        </th>
                        <th>

                        </th>


                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderHeader.Id)
                            </td>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderHeader.PickupName)
                            </td>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderHeader.ApplicationUser.Email)
                            </td>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderHeader.PickupTime)
                            </td>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderHeader.OrderTotal)
                            </td>
                            <td class='text-right'>
                                @Html.DisplayFor(m => item.OrderDetails.Count)
                            </td>
                            <td>
                                <button type="button"  class="btn btn-success anchorDetails" data-id="@item.OrderHeader.Id" data-toggle="modal">
                                    <i class="far fa-list-alt"></i>
                                    تفاصيل
                                </button>
                            </td>
                            <td>
                            <td>
                                <a asp-action="Invoice" asp-controller="ManageOrder" class="btn btn-info" asp-route-id="@item.OrderHeader.Id">

                                    <i class="far fa-list-alt"></i>
                                    فاتوره
                                </a>

                            </td>
                        </tr>
                    }
                </table>
            }
            else
            {
                <h1 class='text-center'>
                   لا توجد طلبات الأن...
                </h1>
            }
        </div>
    </div>

</form>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-idden="true">
    <div class="modal-dialog-centered modal-dialog" style="max-width:1000px" role="document">
        <div class="modal-content">
            <div class="modal-header bg-success text-light ">
                <div class="col-10 offset-1 tex-right">
                    <center><h5 class="modal-title">تفاصيل الطلب</h5></center>
                </div>
                <div class="col-1">
                    <button type="button" class="float-right btn-outline-secondary close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
            <div class="modal-body justify-content-center" id="myModalContent">

            </div>

        </div>
    </div>
</div>


@section scripts{
    <script>

        var PostBackURL = '/Customer/Order/GetOrderDetails';
        $(function () {
            $(".anchorDetails").click(function () {
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "Get",
                    url: PostBackURL,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    cache: false,
                    dataType: "html",
                    success: function (data) {
                        $('#myModalContent').html(data);
                        $('#myModal').modal('show');

                    },
                    error: function () {
                        alert("Dynamic content load failed");
                    }

                });
            });
        });
    </script>
}